name: build nut multi-arch images

on:
  push:
    branches: master
  ma

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Docker login
          run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: build the image
        run: |
        docker buildx build --push \
          --tag edgd1er/nut-stats:latest \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          ./Build
