name: lint dockerfile

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '.github/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2.4.0
      - name: hadolint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: ./Build/Dockerfile
